spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  servlet:
    context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: d:/spring-boot-log/
#  level: debug
mybatis:
  mapper-locations: classpath:mapper/mybatis/*.xml
  configuration:
#    配置打印mybatis的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  file: d:/spring-boot-log/sell/ (该配置与path效果一样，选其一配置即可)